# Generated by Django 3.1.7 on 2021-03-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetdata',
            old_name='likes',
            new_name='friend_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='enter',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='body',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='postdate',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='screenname',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='tweetid',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='url',
        ),
    ]
