# Generated by Django 3.1.7 on 2021-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210314_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdata',
            name='friend_id',
            field=models.TextField(),
        ),
    ]
