# Generated by Django 3.1.7 on 2021-03-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210314_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdata',
            name='friend_id',
        ),
    ]
