# Generated by Django 3.1.7 on 2021-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210314_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendFriendID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_friend_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tweetdata',
            name='profile_image_url',
            field=models.TextField(),
        ),
    ]
